config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  get 'store/index'
  resources :products
  root "store#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
                          with: %r{\.(gif|jpg|png)\z}i,
                          message: "must be a URL for GIF, JPG or PNG image.",
                        }
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item

  private

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line Items present")
      throw :abort
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  private

  def set_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: %i[ show edit update destroy ]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    @line_item = LineItem.new(line_item_params)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to line_item_url(@line_item), notice: "Line item was successfully created." }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to line_item_url(@line_item), notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url, notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Product.order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carts</h1>

<div id="carts">
  <% @carts.each do |cart| %>
    <%= render cart %>
    <p>
      <%= link_to "Show this cart", cart %>
    </p>
  <% end %>
</div>

<%= link_to "New cart", new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cart %>

<div>
  <%= link_to "Edit this cart", edit_cart_path(@cart) %> |
  <%= link_to "Back to carts", carts_path %>

  <%= button_to "Destroy this cart", @cart, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>ShoppingCart</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
		<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
		<%= javascript_importmap_tags %>
	</head>
	<%= render partial: "shared/navbar" %>
	<%= render partial: "shared/header" %>
	<body>
		<div class="container">
			<h1> <%= @page_title %> </h1>
			<%= yield %>
		</div>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
	</body>
</html>

app/views/line_items/_form.html.erb
<%= form_with(model: line_item) do |form| %>
  <% if line_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :cart_id, style: "display: block" %>
    <%= form.text_field :cart_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<div id="<%= dom_id line_item %>">
  <p>
    <strong>Product:</strong>
    <%= line_item.product_id %>
  </p>

  <p>
    <strong>Cart:</strong>
    <%= line_item.cart_id %>
  </p>

</div>

app/views/line_items/edit.html.erb
<h1>Editing line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Show this line item", @line_item %> |
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Line items</h1>

<div id="line_items">
  <% @line_items.each do |line_item| %>
    <%= render line_item %>
    <p>
      <%= link_to "Show this line item", line_item %>
    </p>
  <% end %>
</div>

<%= link_to "New line item", new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @line_item %>

<div>
  <%= link_to "Edit this line item", edit_line_item_path(@line_item) %> |
  <%= link_to "Back to line items", line_items_path %>

  <%= button_to "Destroy this line item", @line_item, method: :delete %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
	<% if product.errors.any? %>
		<div style="color: red">
			<h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
			<ul>
				<% product.errors.each do |error| %>
					<li><%= error.full_message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div>
		<%= form.label :title, style: "display: block" %>
		<%= form.text_field :title %>
	</div>
	<div>
		<%= form.label :description, style: "display: block" %>
		<%= form.text_area :description, rows:10, cols:10  %>
	</div>
	<div>
		<%= form.label :image_url, style: "display: block" %>
		<%= form.text_field :image_url %>
	</div>
	<div>
		<%= form.label :price, style: "display: block" %>
		<%= form.text_field :price %>
	</div>
	<div>
		<%= form.submit %>
	</div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Title:</strong>
    <%= product.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= product.image_url %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<% if notice %>
	<aside class="alert">  <%= notice %></aside>
<% end %>
<h1>Products</h1>
<div class = "container">
	<table class="table table-striped">
		<tbody>
			<% @products.each do |product| %>
				<tr class="<%= cycle('table-primary', 'table-secondary') %>">
					<td> <%= image_tag(product.image_url, class: 'img-thumbnail') %>
					</td>
					<td class="description">
						<h1><%= product.title %></h1>
						<p> <%= truncate(strip_tags(product.description), length: 80) %> </p>
					</td>
					<td>
						<ul class ="list-group-item">
							<li class ="list-group-item"><%= link_to 'Show', product %></li>
							<li class ="list-group-item"><%= link_to 'Edit', edit_product_path(product) %></li>
							<li class ="list-group-item">
								<%= link_to 'Destroy', product, method: :delete, data: { turbo_confirm: 'Are You Sure You want to delete this product?' }, class: "button is-dark" %>
							</li>
						</ul>
					</td>
				</tr>
			<% end %>
		</tbody>
		<tfoot>
			<tr>
				<td colspan="3">
					<%= link_to 'New Product', new_product_path %>
				</td>
			</tr>
		</tfoot>
	</table>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p class ="alert alert-info mt-4", style="color: green"><%= notice %></p>
<%= render @product %>
<div>
	<%= link_to "Edit this product", edit_product_path(@product) %> |
	<%= link_to "Back to products", products_path %>
	<%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/shared/_flash.html.erb
<%if flash[:notice]%>
	<div class = "alert alert-info mt-4" role = "alert">
		<%= flash[:notice]%>
	</div>
<%end%>
<%if flash[:alert]%>
	<div class = "alert alert-warning mt-4" role = "alert">
		<%= flash[:alert]%>
	</div>
<%end%>

app/views/shared/_header.html.erb
<div class="card">
	<h5 class="card-header">Welcome Mine</h5>
	<div class="card-body">
		<h5 class="card-title">Great Quote</h5>
		<p class="card-text">We are not of they who give up, but those who through hard work and persistence bring their dreams to reality</p>
		<a href="#" class="btn btn-primary">See More</a>
	</div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
	<div class="container-fluid">
		<%= link_to image_tag("logo.svg", alt: "Logo", width: "30", height: "24", class: "d-inline-block align-text-top") + " Danitex", root_path, class: "navbar-brand" %>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<%= link_to "Home", root_path, class: "nav-link active", "aria-current": "page" %>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Questions</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">News</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Contact</a>
				</li>
			</ul>
			<form class="d-flex" role="search">
				<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
				<button class="btn btn-outline-success" type="submit">Search</button>
			</form>
		</div>
	</div>
</nav>

app/views/store/index.html.erb
<% if notice %>
	<aside id="notice"><%= notice %></aside>
<% end %>
<div class="container">
	<h1>Welcome To My Catalog My Very Best</h1>
	<ul class="list-group">
		<% cache @products do %>
			<% @products.each do |product| %>
				<% cache product do %>
					<li class = "list-group">
						<div class="container">
							<div class="row grid gap-0 row-gap-3">
								<div class="col p-2 g-col-6">
									<%= image_tag(product.image_url, class: "rounded float-start") %>
								</div>
								<div class="col-6 p-2 g-col-6">
									<h2><%= product.title %></h2>
									<p>
										<%= sanitize(product.description) %>
									</p>
									<div class="price">
										<%= number_to_currency(product.price) %>
									</div>
								</div>
							</div>
						</div>
					</li>
				<% end %>
			<% end %>
		<% end %>
	</ul>
</div>